### ISSUE TITLE
Problem with permissions (in op)

### ISSUE THREAD

**Issue by Alexroge** [LielAmar/CompletePermissions#2]
Hey,
I am a developer, and I downloaded the source code for your plugin and trying the plugin (without modifying the code). It works well, the problem, even being OP, impossible to make commands, without entering the permissions (bukkit) in the group.
Is there a place in your source code to override this?

![2020-11-15_00 51 12](https://user-images.githubusercontent.com/11699505/99159458-ca158280-26dc-11eb-9f38-29b0d272a873.png)

**Comment by LielAmar** [comment]
Hi Alexroge :)
It's been a while since I wrote the **CustomPermissions** & **PermissibleInjector** classes, which are the ones you are looking for.
You can find them [here](https://github.com/LielAmar/CompletePermissions/tree/master/src/com/lielamar/completepermissions/permission).

Basically, what you want to do is override the **hasPermissions** method in **CustomPermission** and remove my implementation of it (checking if the player has the permission regardless of them being op).

The new method should have this:
**if(this.player.isOp()) return true;**

**Comment by Alexroge** [comment]
> 
> 
> Hi Alexroge :)
> It's been a while since I wrote the **CustomPermissions** & **PermissibleInjector** classes, which are the ones you are looking for.
> You can find them [here](https://github.com/LielAmar/CompletePermissions/tree/master/src/com/lielamar/completepermissions/permission).
> 
> Basically, what you want to do is override the **hasPermissions** method in **CustomPermission** and remove my implementation of it (checking if the player has the permission regardless of them being op).
> 
> The new method should have this:
> **if(this.player.isOp()) return true;**

It's work fine ! Thank you very much for your help!
